### ISSUE TITLE
#nii, #robot .title

### ISSUE THREAD

**Issue by levlevin** [rk-bmstu/rkbmstu#1]
Тайтлы НИИ и робота не залезают как должны на предыдущую секцию. Сейчас я форсю fix-margin'ом, но это явно не дело. Мне кажется косяк в том что где-то есть бэкграунд имг, а где-то — нет. Может сработает если везде жестко проставить бг и z-index?
@BOPOHOB

**Comment by BOPOHOB** [comment]
проблема точно в z-index. в каком это браузере?

**Comment by levlevin** [comment]
Не совсем, но как перекроил структуру — заработало как и должно было.
